# Generated by Django 5.0.6 on 2024-05-16 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executers', '0002_executers_rating'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executers',
            new_name='Executer',
        ),
    ]
