# Generated by Django 5.0.6 on 2024-05-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executers', '0004_rename_executer_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='rating',
        ),
    ]
