<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-16 21:18

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.0.3 on 2024-04-21 15:02

import django.db.models.deletion
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('freelance', '0008_remove_order_order_taken_remove_order_order_taken_at'),
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
=======
                ('testimonials', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.customer')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.executor')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
            },
        ),
    ]
