"""
Django settings for config project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 5.0.6.
=======
Generated by 'django-admin startproject' using Django 5.0.3.
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

<<<<<<< HEAD
import os
from pathlib import Path
from environs import Env

# Инициализация environs
env = Env()
env.read_env()
=======
from pathlib import Path


from config.ddtb import DEBUG_PANEL_MIDDLE_WARE, DEBUG_TOOLBAR_PANELS_SETTINGS
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
=======
SECRET_KEY = "django-insecure-@)xskplmy@5=ihx%r9xk2-ktc=n$l13+-a*4(o(@yid%nhl7p6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
<<<<<<< HEAD
    # My Apps
    # "users",
    # "customers",
    # "executers",
    # "orders",
    # "ratings",
    # "services",
=======
    "debug_toolbar",
    "rest_framework",
    "djoser",
    "corsheaders",
    # My apps
    "freelance",
    "ratings",
    "services",
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
<<<<<<< HEAD
]

ROOT_URLCONF = "config.urls"
ROOT_URLCONF = 'your_project.urls'
WSGI_APPLICATION = 'your_project.wsgi.application'
=======
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    DEBUG_PANEL_MIDDLE_WARE,
]


ROOT_URLCONF = "config.urls"
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
<<<<<<< HEAD
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
=======
                "django.template.context_processors.request",  # Добавьте этот контекстный процессор
                "django.contrib.auth.context_processors.auth",  # Убедитесь, что этот контекстный процессор включен
                "django.contrib.messages.context_processors.messages",  # Убедитесь, что этот контекстный процессор включен
                # Добавьте любые другие контекстные процессоры, которые вам могут быть нужны
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
<<<<<<< HEAD
        
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('DATABASE_NAME'),
        'USER': env.str('DATABASE_USER'),
        'PASSWORD': env.str('DATABASE_PASSWORD'),
        'HOST': env.str('DATABASE_HOST', default='localhost'),
        'PORT': env.int('DATABASE_PORT', default=5432),
=======
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Almaty"

<<<<<<< HEAD
=======
USE_L10N = True

>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
USE_I18N = True

USE_TZ = True

<<<<<<< HEAD
USE_L10N = True
=======
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

<<<<<<< HEAD
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
=======
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static"
]  # Укажите путь к вашей директории со статическими файлами


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"  # Укажите путь к вашей директории с медиафайлами
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

<<<<<<< HEAD
AUTH_USER_MODEL = "users.CustomUser"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env.str('EMAIL_HOST')
EMAIL_PORT = env.int('EMAIL_PORT')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL')

EMAIL_HOST = 'smtp.example.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD')


=======

# Corsheaders
CORS_ALLOWED_ORIGINS = [
    "https://example.com",
    "https://sub.example.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
# LOGOUT_URL = 'logout'
# LOGOUT_REDIRECT_URL = 'freelance:login'
>>>>>>> ffce688842ec1fa75373b03dbab3af6db23f1b1a
