# Generated by Django 5.0.6 on 2024-05-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rating',
        ),
    ]
