# Generated by Django 5.0.6 on 2024-05-17 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executers', '0003_rename_executers_executer'),
        ('orders', '0003_rename_orders_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executer',
            new_name='Executor',
        ),
    ]
