# Generated by Django 5.0.6 on 2024-05-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_customers_customer'),
        ('executers', '0003_rename_executers_executer'),
        ('orders', '0002_alter_orders_executor'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
