# Generated by Django 5.0.6 on 2024-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Взят на выполнение'),
        ),
    ]
