# Generated by Django 5.0.6 on 2024-05-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executers', '0003_rename_executers_executer'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_profile', to='executers.executer', verbose_name='Исполнитель'),
        ),
    ]
